create table person
(
    id            int primary key GENERATED BY DEFAULT AS IDENTITY,
    username      varchar(100) NOT NULL,
    year_of_birth int          NOT NULL,
    password      varchar      not null
);

insert into person (username, year_of_birth, password,role)
values ('qwer', 1991, 'qwer', 'ROLE_USER');

insert into person (username, year_of_birth, password)
values ('qwer', 2000, 'qwer');