create table person
(
    id            int primary key GENERATED BY DEFAULT AS IDENTITY,
    username      varchar(100) NOT NULL,
    year_of_birth int          NOT NULL,
    password      varchar      not null
);

insert into person (username, year_of_birth, password, role)
values ('qwer', 1991, 'qwer', 'ROLE_USER');

insert into person (username, year_of_birth, password)
values ('qwer', 2000, 'qwer');

alter table "online-store".users
    add unique (email);

create sequence "online-store-backup".cart_id_seq;

alter sequence "online-store-backup".cart_id_seq owner to postgres;

alter sequence "online-store-backup".cart_id_seq owned by "online-store-backup".cart.id;

create sequence "online-store-backup".categories_id_seq;

alter sequence "online-store-backup".categories_id_seq owner to postgres;

alter sequence "online-store-backup".categories_id_seq owned by "online-store-backup".categories.id;

create sequence "online-store-backup".orders_id_seq;

alter sequence "online-store-backup".orders_id_seq owner to postgres;

alter sequence "online-store-backup".orders_id_seq owned by "online-store-backup".orders.id;

create sequence "online-store-backup".products_id_seq;

alter sequence "online-store-backup".products_id_seq owner to postgres;

alter sequence "online-store-backup".products_id_seq owned by "online-store-backup".products.id;

create sequence "online-store-backup".users_id_seq;

alter sequence "online-store-backup".users_id_seq owner to postgres;

alter sequence "online-store-backup".users_id_seq owned by "online-store-backup".users.id;

